Add polynomials + reduction
nikitonsky/groebner pull request #1
Opened 2020-09-13 11:14 UTC by nikitonsky

Пока смотреть только на саму архитектуру + элементарную редукцию/редукцию полинома по полиному

2020-10-01 15:26 UTC, DimaTrushin requested changes
Я прошелся по коду. Сделал несколько замечаний. Если замечание применимо к нескольким местам, я его не повторял.
Основная фатальная проблема в дизайне наблюдается в самом конце (где множества многочленов). А так ты местами в публичный интерфейс классов запихиваешь то, чего там быть не должно или какие-нибудь дурацкие конструкторы, которых быть не должно и так далее.
В самом конце у тебя класс множества полиномов -- это бредовая каша. Надо выделить отдельный объект ответственный за алгоритмы. Кроме того, порядок на полиномах не удовлетворяет необходимым условиям, чтобы использовать std::set, он не total.
Часть методов работает кардинально не верно. Я про это добавил замечания.
Алгоритм бухбергера я пока не смотрел. 
У тебя отсутствует возможность задавать кастомные порядки на мономах, все порядки захардкожены в мономы и полиномы. Это надо переделать. Даже если хардкодить лексикографику, то это делать надо НЕ так. Я сделал соответствующие замечания.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +          if (monom % otherLeadTerm.monom) {
Вот он этот неизвестный и непонятный метод. Куда читаемее было бы
monom.isDivisibleBy(otherLeadTerm.monom)
Кстати monomial, а не monom.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  void reduct(const Polynomial<T, vars>& other) {
плохое название и сигнатура.
Тогда уж
bool tryCompletelyReduceBy(...)
Во-первых, глагол в названии.
Во-вторых, ты еще и проверишь была ли хотя бы одна редукция.
В-третьих, будет понятно, что ты не просто как-то редуцируешь, а редуцируешь максимально.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +          reduct(*it);
it->reduct();
в твоем случае. Ибо так как написано, оно ничего не делает, а просто создает временный объект и игнорирует его.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  friend Polynomial<T, vars> makeSPolynomial(const Polynomial<T, vars>& one,
Этого метода не должно быть у полинома. Вынести как и все редукции.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  bool isZero() const {
Очень хороший метод. Вот его бы в термы еще добавить.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  bool operator==(const Polynomial& other) const {
где сравнение на неравенство?

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +      return data_ == other.data_;
Без удаления нулевых термов это неверный метод сравнения.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  bool same(const Polynomial& other) const {
Вот это вообще не понятно что значит. Как по названию догадаться, что ты тут проверяешь? Даже глядя на имплементацию, я не понимаю что это за метод. При этом используется leadTerm, который зависит от порядка.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  void garbageCollect_() {
Изменить имя.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +          if (it->second == T())
Вот тут плохо. Почему коэффициент поля по умолчанию -- это нулевой?
Тут я бы ожидал что-то вроде
it->second == T(0)
Потому что для поля мы ожидаем, что int константы конвертятся в элементы поля, а если нет, то хотя бы ошибка компиляции, а не непонятное действие.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  std::map<Monomial<vars>, T> data_;
Стоит поменять имя data_ на terms_

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +public:
using-ги

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  PolynomialSet() {}
PolynomialSet() = default;

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  PolynomialSet(const std::set<Polynomial<T, vars>>& data) : data_(std::copy(data)) {}
Зачем тут std::copy? Ты явно это не компилил и не тестил. Оно даже сработать не должно. Тут просто data_(data). В c++ copy by default.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  PolynomialSet(std::set<Polynomial<T, vars>>&& data) : data_(data) {}
Здесь должен быть data_(std::move(data))

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  PolynomialSet(std::set<Polynomial<T, vars>>&& data) : data_(data) {}
Оба конструктора плохие. Лучше уж тогда через std::initializer_list делать либо std::set принимать by value и делать move внутрь множества многочленов.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  std::set<Polynomial<T, vars>> data_;
Плохо использовать set для многочленов, так как их порядок не total (у тебя есть эквивалентные). Надо какой-то порядок на поэффициентах использовать тогда.
Кроме того, у тебя порядок должен быть не частью многочлена тогда, а передаваться тут в set непосредственно.
Ну и название data_ -- заменить на более подходящее.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  std::vector<Polynomial<T, vars>> asVector() const {
Нахрена этот метод? Ты создаешь копию всех многочленов и в вектор кладешь. Где это понадобится?

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  const std::set<Polynomial<T, vars>>& data() const {
С чего вдруг нужен доступ к данным внутри множества? Вдруг ты поменяешь имплементацию и сделаешь unordered_set и у тебя упадет контракт с клиентом твоей библиотеки. Убрать.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  bool operator==(const PolynomialSet& other) const {
Сравнение на неравенство.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  PolynomialSet(std::set<Polynomial<T, vars>>&& data) : data_(data) {}
У тебя должны быть инварианты, что нет нулевых многочленов в множестве, иначе сравнение не верно работает. Инварианты!

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +      data_.insert(polynom);
привет добавление эквивалентных полиномов.

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  friend std::vector<Polynomial<T, vars>> makeSPolynoms(const PolynomialSet<T, vars>& polynoms) {
Какого хрена этот метод делает в публичном интерфейсе множества?

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +      for (auto& polynom: makeSPolynoms(*this)) {
Привет undefined behaviour. Это известный косяк for в c++. Дело в том, что временный объект в правой части от : существует только в шапке цикла, но НЕ существует в теле цикла! Вот тут про это можно послушать
https://youtu.be/TFMKjL38xAI?t=2631

2020-10-01 15:26 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +class PolynomialSet {
Этот класс -- это каша из всего подряд. Он не выполняет одну задачу. делает кучу всего, содержит кучу ненужного в публичном интерфейсе. Советую посмотреть про SOLID вот это видео
https://www.youtube.com/watch?v=Ntraj80qN2k&ab_channel=CppCon

2020-10-01 15:46 UTC, nikitonsky commented on include/groebner/polynomial.h
> +  PolynomialSet(std::set<Polynomial<T, vars>>&& data) : data_(data) {}
У std::set есть конструктор с move-сематикой https://en.cppreference.com/w/cpp/container/set/set 4-й, стало быть он и позовется

2020-10-02 08:45 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  PolynomialSet(std::set<Polynomial<T, vars>>&& data) : data_(data) {}
Ты неправильно понимаешь работу move семантики. Это ожидаемо. Смотри, работа плюсов завязана на overload resolution. Давай объясню, как она тут работает.
Строчка 
: data_(data) {
эквивалентна строчке
std::set < Polynomial < T, vars > > data_(data);
В этом случае это выражение рассматривается компилятором так
Type variable(expression);
Тогда компилятор сначала вычисляет expression, чтобы определить тип возращаемого значения от expression (а НЕ тип expression), а потом подбирает лучший конструктор по типу. В твоем случае data является ссылкой (rvalue reference). Любая ссылка в плюсах интерпретируется как expression. И когда ссылка вычисляется, то она ссылается на объект, который по определению lvalue всегда! Потому в строчке
std::set < Polynomial < T, vars > > data_(data);
у тебя будет вызван copy constructor, а не move constructor, как ты ожидаешь. Потому всегда надо кастовать в rvalue reference, для правильной перегрузки, то есть писать
std::set < Polynomial < T, vars > > data_(std::move(data));
Это поведение является intentional. Например, если ты передаешь значение by rvalue reference
f(std::move(x));
это означает, что тебе больше не нужно значение x-а и ты его посылаешь в f. Однако, когда f его использует
f(T&& x) {
....
g(x);
...
}
То в строчке вызова g может оказаться, что f сама НЕ хочет передавать свой объект в g by rvalue reference, потому что f все еще нужно значение x. Если f действительно не нуждается в x, она должна это подчеркнуть кастом
f(T&& x) {
....
g(std::move(x));
// нельзя использовать x далее
...
}
Вот тут хорошо объяснено почему это так работает
https://youtu.be/TFMKjL38xAI?t=232

2020-10-05 19:32 UTC, nikitonsky commented on include/groebner/polynomial.h
> +  friend std::vector<Polynomial<T, vars>> makeSPolynoms(const PolynomialSet<T, vars>& polynoms) {
А что не так в фабрике, делающей s-полиномы?

2020-10-05 20:08 UTC, nikitonsky commented on include/groebner/polynomial.h
> +      std::map<Monomial<vars>, T> newData;
А что плохого в умножении полинома на нулевой терм? Ну получим мы нулевой полином

2020-10-05 20:39 UTC, nikitonsky commented on include/groebner/polynomial.h
> +          data_[term.monom] += term.coeff;
У меня инвариант - в полиноме нету 2 одинаковых термов

2020-10-05 20:40 UTC, nikitonsky commented on include/groebner/polynomial.h
> +      data_.insert(polynom);
А какой смысл в множестве полиномов хранить одинаковые полиномы?

2020-10-05 20:42 UTC, nikitonsky commented on include/groebner/polynomial.h
> +          reduct(*it);
Тут я редуцирую текущий полином по *it, все правильно

2020-10-05 21:45 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +  friend std::vector<Polynomial<T, vars>> makeSPolynoms(const PolynomialSet<T, vars>& polynoms) {
В фабрике проблем нет. Просто это не должен делать класс PolynomialSet. Вообще это не его зона ответственности, за это как минимум должен отвечать другой объект вроде алгоритмов или свободная функция.

2020-10-05 21:49 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +      std::map<Monomial<vars>, T> newData;
Важнее, что мы получим много термов с неединичной мономильной частью и нулевым коэффициентом. А если ты допускаешь такие термы, то их нельзя сравнивать так, как у тебя написан оператор сравнения. Кроме того, все такие термы являются эквивалентными представителями нуля. Это говно обязательно вылезет в виде неожиданной ошибки в алгоритме.

2020-10-05 21:53 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +          data_[term.monom] += term.coeff;
Ты не понял. В векторе термы могут повторяться. Сигнатура функции никак не запрещает terms набить одним и тем же, можно хоть эквивалентными версиями нулевого терма, хоть одним и тем же повторяющимся термом. Это вопрос дизайна, что мы хотим. Либо мы неявно складываем слагаемые, либо мы ругаемся на это. В любом случае вектор в качестве аргумента для конструктора выглядит очень странно. Особенно в виде публичного конструктора. Вряд ли кто будет строить многочлен из вектора. Из списка инициализации еще пожалуйста, но из вектора.
А еще я бы рекомендовал поддерживать инвариант, что нет термов с нулевым коэффициентом. И вообще запретилв бы термы с нулевым коэффициентом кроме когда мономиальная часть единица.
Замечание про emplace это не снимает.

2020-10-05 21:54 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +      data_.insert(polynom);
Этот вопрос снялся, я не заметил, что у тебя порядок полный на многочленах. Но все порядки надо вынести будет в отдельные классы, ибо ты не хочешь иметь порядок по умолчанию. Кроме того, поле может не иметь встроенного порядка по умолчанию.

2020-10-05 22:00 UTC, DimaTrushin commented on include/groebner/polynomial.h
> +          reduct(*it);
Господи, у тебя куча одноименных методов делающих разные вещи
  void reduct(const Polynomial<T, vars>& other) {
  friend Polynomial reduct(const Polynomial& polynom) {
Вот догадайся, какой из них вызовется. Я бы ждал ambiguous call.
Это к вопросу о читаемости кода и использовании плохих имен. 
Функции -- это действия, их имена должны содержать глаголы. Здесь принят глагол reduce для этой процедуры. Но все равно надо различать reduce_me_completely от reduce_by.

2020-10-06 18:49 UTC, nikitonsky commented on include/groebner/polynomial.h
> +  friend std::vector<Polynomial<T, vars>> makeSPolynoms(const PolynomialSet<T, vars>& polynoms) {
Ну эта фабрика работает с PolynomialSet, поэтому я ее туда запихнул
+ она ходит в приватные поля класса

2020-10-06 20:08 UTC, nikitonsky commented on include/groebner/polynomial.h
> +  const std::set<Polynomial<T, vars>>& data() const {
Завел методы begin() и end() чтобы проитерироваться

2020-10-06 20:13 UTC, nikitonsky commented on include/groebner/polynomial.h
> +  std::map<Monomial<vars>, T> data_;
Ну тут маппинг из Term -> Coeff, не уверен, что стоит

2020-10-08 20:43 UTC, merged